DELETE FROM "highscores";
DELETE FROM "countries";

INSERT INTO "highscores" ("id", "playername", "score") VALUES
(0, "LUNARLANDER", 94),
(1, "lowercase", 85),
(2, "PeriginTuck", 89);

INSERT INTO "countries" ("id", "name", "alpha_2", "alpha_3", "capital") VALUES
(4,"Afghanistan","af","afg", "Kabul"),
(8,"Albania","al","alb", "Tirana"),
(12,"Algeria","dz","dza", "Algiers"),
(20,"Andorra","ad","and", "Andorra la Vella"),
(24,"Angola","ao","ago", "Luanda"),
(28,"Antigua and Barbuda","ag","atg", "Saint John's"),
(32,"Argentina","ar","arg", "Buenos Aires"),
(51,"Armenia","am","arm", "Yerevan"),
(36,"Australia","au","aus", "Canberra"),
(40,"Austria","at","aut", "Vienna"),
(31,"Azerbaijan","az","aze", "Baku"),
(44,"Bahamas","bs","bhs", "Nassau"),
(48,"Bahrain","bh","bhr", "Manama"),
(50,"Bangladesh","bd","bgd", "Dhaka"),
(52,"Barbados","bb","brb", "Bridgetown"),
(112,"Belarus","by","blr", "Minsk"),
(56,"Belgium","be","bel", "Brussels"),
(84,"Belize","bz","blz", "Belmopan"),
(204,"Benin","bj","ben", "Porto-Novo"),
(64,"Bhutan","bt","btn", "Thimpu"),
(68,"Bolivia (Plurinational State of)","bo","bol", "La Paz, Sucre"),
(70,"Bosnia and Herzegovina","ba","bih", "Sarajevo"),
(72,"Botswana","bw","bwa", "Gabarone"),
(76,"Brazil","br","bra", "Brasilia"),
(96,"Brunei Darussalam","bn","brn", "Bandar Seri Begawan"),
(100,"Bulgaria","bg","bgr", "Sofia"),
(854,"Burkina Faso","bf","bfa", "Ouagadougou"),
(108,"Burundi","bi","bdi", "Bujumbura"),
(132,"Cabo Verde","cv","cpv", "Praia"),
(116,"Cambodia","kh","khm", "Phnom Penh"),
(120,"Cameroon","cm","cmr", "Yaounde"),
(124,"Canada","ca","can", "Ottawa"),
(140,"Central African Republic","cf","caf", "Bangui"),
(148,"Chad","td","tcd", "N'Djamena"),
(152,"Chile","cl","chl", "Santiago"),
(156,"China","cn","chn", "Beijing"),
(170,"Colombia","co","col", "Bogota"),
(174,"Comoros","km","com", "Moroni"),
(178,"Congo","cg","cog", "Brazzaville"),
(180,"Congo, Democratic Republic of the","cd","cod", "Kinshasa"),
(188,"Costa Rica","cr","cri", "San Jose"),
(384,"Côte d'Ivoire","ci","civ", "Yamoussoukro, Abidjan"),
(191,"Croatia","hr","hrv", "Zagreb"),
(192,"Cuba","cu","cub", "Havana"),
(196,"Cyprus","cy","cyp", "Nicosia"),
(203,"Czechia","cz","cze", "Prague"),
(208,"Denmark","dk","dnk", "Copenhagen"),
(262,"Djibouti","dj","dji", "Djibouti"),
(212,"Dominica","dm","dma", "Roseau"),
(214,"Dominican Republic","do","dom", "Santo Domingo"),
(218,"Ecuador","ec","ecu", "Quito"),
(818,"Egypt","eg","egy", "Cairo"),
(222,"El Salvador","sv","slv", "San Salvador"),
(226,"Equatorial Guinea","gq","gnq", "Malabo"),
(232,"Eritrea","er","eri", "Asmara"),
(233,"Estonia","ee","est", "Tallinn"),
(748,"Eswatini","sz","swz", "Mbabane, Lobamba"),
(231,"Ethiopia","et","eth", "Addis Ababa"),
(242,"Fiji","fj","fji", "Suva"),
(246,"Finland","fi","fin", "Helsinki"),
(250,"France","fr","fra", "Paris"),
(266,"Gabon","ga","gab", "Libreville"),
(270,"Gambia","gm","gmb", "Banjul"),
(268,"Georgia","ge","geo", "Tbilisi"),
(276,"Germany","de","deu", "Berlin"),
(288,"Ghana","gh","gha", "Accra"),
(300,"Greece","gr","grc", "Athens"),
(308,"Grenada","gd","grd", "Saint George's"),
(320,"Guatemala","gt","gtm", "Guatemala City"),
(324,"Guinea","gn","gin", "Conakry"),
(624,"Guinea-Bissau","gw","gnb", "Bissau"),
(328,"Guyana","gy","guy", "Georgetown"),
(332,"Haiti","ht","hti", "Port-au-Prince"),
(340,"Honduras","hn","hnd", "Tegucigalpa"),
(348,"Hungary","hu","hun", "Budapest"),
(352,"Iceland","is","isl", "Reykjavik"),
(356,"India","in","ind", "New Delhi"),
(360,"Indonesia","id","idn", "Jakarta"),
(364,"Iran (Islamic Republic of)","ir","irn", "Tehran"),
(368,"Iraq","iq","irq", "Badhdad"),
(372,"Ireland","ie","irl", "Dublin"),
(376,"Israel","il","isr", "Jerusalem"),
(380,"Italy","it","ita", "Rome"),
(388,"Jamaica","jm","jam", "Kingston"),
(392,"Japan","jp","jpn", "Tokyo"),
(400,"Jordan","jo","jor", "Amman"),
(398,"Kazakhstan","kz","kaz", "Astana"),
(404,"Kenya","ke","ken", "Nairobi"),
(296,"Kiribati","ki","kir", "Tarawa Atoll"),
(408,"Korea (Democratic People's Republic of)","kp","prk", "Pyongyang"),
(410,"Korea, Republic of","kr","kor", "Seoul"),
(414,"Kuwait","kw","kwt", "Kuwait City"),
(417,"Kyrgyzstan","kg","kgz", "Bishkek"),
(418,"Lao People's Democratic Republic","la","lao", "Vientiane"),
(428,"Latvia","lv","lva", "Riga"),
(422,"Lebanon","lb","lbn", "Beirut"),
(426,"Lesotho","ls","lso", "Maseru"),
(430,"Liberia","lr","lbr", "Monrovia"),
(434,"Libya","ly","lby", "Tripoli"),
(438,"Liechtenstein","li","lie", "Vaduz"),
(440,"Lithuania","lt","ltu", "Vilnius"),
(442,"Luxembourg","lu","lux", "Luxembourg"),
(807,"Macedonia, the former Yugoslav Republic of","mk","mkd", "Skopje"),
(450,"Madagascar","mg","mdg", "Antananarivo"),
(454,"Malawi","mw","mwi", "Lilongwe"),
(458,"Malaysia","my","mys", "Kuala Lumpur"),
(462,"Maldives","mv","mdv", "Male"),
(466,"Mali","ml","mli", "Bamako"),
(470,"Malta","mt","mlt", "Valletta"),
(584,"Marshall Islands","mh","mhl", "Majuro"),
(478,"Mauritania","mr","mrt", "Nouakchott"),
(480,"Mauritius","mu","mus", "Port Louis"),
(484,"Mexico","mx","mex", "Mexico City"),
(583,"Micronesia (Federated States of)","fm","fsm", "Palikir"),
(498,"Moldova, Republic of","md","mda", "Chisinau"),
(492,"Monaco","mc","mco", "Monaco"),
(496,"Mongolia","mn","mng", "Ulaanbaatar"),
(499,"Montenegro","me","mne", "Podgorica"),
(504,"Morocco","ma","mar", "Rabat"),
(508,"Mozambique","mz","moz", "Maputo"),
(104,"Myanmar","mm","mmr", "Naypyidaw"),
(516,"Namibia","na","nam", "Windhoek"),
(520,"Nauru","nr","nru", "Yaren"),
(524,"Nepal","np","npl", "Kathmandu"),
(528,"Netherlands","nl","nld", "Amsterdam"),
(554,"New Zealand","nz","nzl", "Wellington"),
(558,"Nicaragua","ni","nic", "Managua"),
(562,"Niger","ne","ner", "Niamey"),
(566,"Nigeria","ng","nga", "Abuja"),
(578,"Norway","no","nor", "Oslo"),
(512,"Oman","om","omn", "Muscat"),
(586,"Pakistan","pk","pak", "Islamabad"),
(585,"Palau","pw","plw", "Melekeok"),
(591,"Panama","pa","pan", "Panama City"),
(598,"Papua New Guinea","pg","png", "Port Moresby"),
(600,"Paraguay","py","pry", "Asuncion"),
(604,"Peru","pe","per", "Lima"),
(608,"Philippines","ph","phl", "Manila"),
(616,"Poland","pl","pol", "Warsaw"),
(620,"Portugal","pt","prt", "Lisbon"),
(634,"Qatar","qa","qat", "Doha"),
(642,"Romania","ro","rou", "Bucharest"),
(643,"Russian Federation","ru","rus", "Moscow"),
(646,"Rwanda","rw","rwa", "Kigali"),
(659,"Saint Kitts and Nevis","kn","kna", "Basseterre"),
(662,"Saint Lucia","lc","lca", "Castries"),
(670,"Saint Vincent and the Grenadines","vc","vct", "Kingstown"),
(882,"Samoa","ws","wsm", "Apia"),
(674,"San Marino","sm","smr", "San Marino"),
(678,"Sao Tome and Principe","st","stp", "Sao Tome"),
(682,"Saudi Arabia","sa","sau", "Riyadh"),
(686,"Senegal","sn","sen", "Dakar"),
(688,"Serbia","rs","srb", "Belgrade"),
(690,"Seychelles","sc","syc", "Victoria"),
(694,"Sierra Leone","sl","sle", "Freetown"),
(702,"Singapore","sg","sgp", "Singapore"),
(703,"Slovakia","sk","svk", "Bratislava"),
(705,"Slovenia","si","svn", "Ljubljana"),
(90,"Solomon Islands","sb","slb", "Honiara"),
(706,"Somalia","so","som", "Mogadishu"),
(710,"South Africa","za","zaf", "Pretoria, Cape Town, Bloemfontein"),
(728,"South Sudan","ss","ssd", "Juba"),
(724,"Spain","es","esp", "Madrid"),
(144,"Sri Lanka","lk","lka", "Sri Jayewardenepura Kotte"),
(729,"Sudan","sd","sdn", "Khartoum"),
(740,"Suriname","sr","sur", "Paramaribo"),
(752,"Sweden","se","swe", "Mbabane"),
(756,"Switzerland","ch","che", "Bern"),
(760,"Syrian Arab Republic","sy","syr", "Damascus"),
(762,"Tajikistan","tj","tjk", "Dushanbe"),
(834,"Tanzania, United Republic of","tz","tza", "Dodoma"),
(764,"Thailand","th","tha", "Bangkok"),
(626,"Timor-Leste","tl","tls", "Dili"),
(768,"Togo","tg","tgo", "Tomo"),
(776,"Tonga","to","ton", "Nuku'alofa"),
(780,"Trinidad and Tobago","tt","tto", "Port-of-Spain"),
(788,"Tunisia","tn","tun", "Tunis"),
(792,"Turkey","tr","tur", "Ankara"),
(795,"Turkmenistan","tm","tkm", "Ashgabat"),
(798,"Tuvalu","tv","tuv", "Funafuti"),
(800,"Uganda","ug","uga", "Kampala"),
(804,"Ukraine","ua","ukr", "Kyiv"),
(784,"United Arab Emirates","ae","are", "Abu Dhabi"),
(826,"United Kingdom of Great Britain and Northern Ireland","gb","gbr", "London"),
(840,"United States of America","us","usa", "Washington D.C."),
(858,"Uruguay","uy","ury", "Montevideo"),
(860,"Uzbekistan","uz","uzb", "Tashkent"),
(548,"Vanuatu","vu","vut", "Port-Vila"),
(862,"Venezuela (Bolivarian Republic of)","ve","ven", "Caracas"),
(704,"Viet Nam","vn","vnm", "Hanoi"),
(887,"Yemen","ye","yem", "Sanaa"),
(894,"Zambia","zm","zmb", "Lusaka"),
(716,"Zimbabwe","zw","zwe", "Harare");
